### ISSUE TITLE
I want to know how to generate the gif in your readme, thank you very much...

### ISSUE THREAD

**Issue by jiawei6636** [JohnleeHIT/Brats2019#2]

**Comment by JohnleeHIT** [comment]
its pretty simple,  you can get a gif by using imageio.mimsave() function which needs the imageio package.

**Comment by jiawei6636** [comment]
> its pretty simple, you can get a gif by using imageio.mimsave() function which needs the imageio package.

Thank you, but how to add the mask edge?

**Comment by JohnleeHIT** [comment]
You can check the Class Evaluation in  utils.py.

**Comment by jiawei6636** [comment]
谢谢 哈哈^_^
