### ISSUE TITLE
Why not do N4BiasFieldCorrection?

### ISSUE THREAD

**Issue by zwlshine** [JohnleeHIT/Brats2019#7]
Your code has a function named N4BiasFieldCorrection, but actually you didn't use this function for your data process, why not do bias field correction? 

Must do bias field correction for data process? Thank you very much!

**Comment by JohnleeHIT** [comment]
If you have tried the N4BiasFieldCorrection function(From simpleITK), you will see that the processing is rather slow , approximately 5min a volume, so i do it offline.  However, it actually just improves a little bit, so its ok to remove this process.

**Comment by zwlshine** [comment]
> If you have tried the N4BiasFieldCorrection function(From simpleITK), you will see that the processing is rather slow , approximately 5min a volume, so i do it offline. However, it actually just improves a little bit, so its ok to remove this process.



> If you have tried the N4BiasFieldCorrection function(From simpleITK), you will see that the processing is rather slow , approximately 5min a volume, so i do it offline. However, it actually just improves a little bit, so its ok to remove this process.

**Comment by zwlshine** [comment]
> If you have tried the N4BiasFieldCorrection function(From simpleITK), you will see that the processing is rather slow , approximately 5min a volume, so i do it offline. However, it actually just improves a little bit, so its ok to remove this process.

Great！ Thanks for your answer, good luck!
